name: Deploy to NPM

on:
  release:
    types:
      - published

jobs:

  build:
    name: build & deploy package
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: export branch name
      run: echo "BRANCH_NAME=$(echo "${GITHUB_REF/refs\/heads\/}")" >> $GITHUB_ENV
      shell: bash
    
    - name: Install Packages
      run: npm install

    - name: checkout configuration repository
      uses: actions/checkout@v2
      with:
        repository: connerludlow/megaphone-config
        token: ${{ secrets.MY_GITHUB_PAT }}
        path: megaphone-config

    - name: apply configuration
      run: |
        cp megaphone-config/sdk/prod/.env .env
        rm -rf megaphone-config

    - name: set version
      run: |
        npm version ${{ github.event.release.tag_name }} --no-git-tag-version
    
    - name: babel build
      run: |
        npm run build:package

    - name: change into dist directory
      run: |
        cd dist 

    - name: publish package
      run: |
        npm publish --ignore-scripts
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    
